source 'https://rubygems.org'

gem 'jekyll', '3.9.2'
gem 'exifr'
gem 'mini_magick'
gem 'jekyll-assets'
gem 'jekyll-paginate'
gem 'sprockets'
gem 'sass'
gem 'uglifier'
gem 'tzinfo-data'
gem 'rmagick'
gem 'webrick'
gem 'kramdown-parser-gfm'